lsi: false
highlighter: rouge

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from

sass:
  style: compressed

defaults:
- scope:
    path:            examples
  values:
    sitemap:         false
- scope:
    path:            tutorials
  values:
    sitemap:         false
- scope:
    path:            documentation
  values:
    sitemap:         false
- scope:
    path:            dcmtn
  values:
    sitemap:         false
- scope:
    path:            examples/latest-stable
  values:
    sitemap:         true
- scope:
    path:            tutorials/latest-stable
  values:
    sitemap:         true
- scope:
    path:            documentation/latest-stable
  values:
    sitemap:         true
